mklink /j %~dp0\projects\myaccountMobile\node_modules %~dp0\node_modules
mklink /j %~dp0\projects\screenRecorderFaq\node_modules %~dp0\node_modules
mklink /j %~dp0\projects\lightpdfMobile\node_modules %~dp0\node_modules	
mklink /j %~dp0\projects\myaccount\node_modules %~dp0\node_modules
mklink /j %~dp0\projects\startup\node_modules %~dp0\node_modules	
mklink /j %~dp0\projects\myaccountMobileImbed\node_modules %~dp0\node_modules	
mklink /j %~dp0\projects\airmore-vip\node_modules %~dp0\node_modules
mklink /j %~dp0\projects\unlimited\node_modules %~dp0\node_modules			
mklink /j %~dp0\projects\pdf-service\node_modules %~dp0\node_modules			
