/* Automatically generated by './build-entry.js' */

import Alert from './alert/index.js';
import Aside from './aside/index.js';
import Button from './button/index.js';
import Container from './container/index.js';
import Dialog from './dialog/index.js';
import Main from './main/index.js';
import Card from './card/index.js';
import Footer from './footer/index.js';

const components = [
  Alert,
  Aside,
  Button,
  Container,
  Dialog,
  Main,
  Card,
  Footer,
];

const install = function(Vue, opts = {}) {

    components.map(component => {
        Vue.component(component.name, component);
    });

    Vue.prototype.$ELEMENT = {
        size: opts.size || '',
        zIndex: opts.zIndex || 2000
    };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}
