/* Automatically generated by './build-entry.js' */
import Card from './card/index.js';
import Footer from './footer/index.js';

const components = [
    Card,
    Footer,
];

const install = function (Vue, opts = {}) {
    //locale.use(opts.locale);
    // locale.i18n(opts.i18n);

    components.map((component) => {
        Vue.component(component.name, component);
    });

    Vue.prototype.$ELEMENT = {
        size: opts.size || '',
        zIndex: opts.zIndex || 2000,
    };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

module.exports = {
    version: '1.0.0',
    Card,
    Footer,
};

module.exports.default = module.exports;
